name: conttrol_asistencia
description: App de Control de Asistencia con Geofencing
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP y manejo de APIs
  http: ^1.2.1
  dio: ^5.4.3+1

  # Geolocalización
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # Estado y preferencias
  provider: ^6.1.1
  shared_preferences: ^2.5.3

  # Reportes y almacenamiento 
  file_saver: ^0.1.1
  path_provider: ^2.1.5 
  open_filex: ^4.3.2
  excel: ^4.0.6
  pdf: ^3.11.3

  # Notificaciones
  flutter_local_notifications: ^19.4.1

  # Utilidades
  intl: ^0.20.2
  permission_handler: ^12.0.1

  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.3.0

  # JSON y serialización
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
    - assets/images/logo1.jpg 
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf